openapi: 3.1.0
info:
  version: 1.0.0
  title: PhoneBook
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    PhoneBook is a contact management application. Which allows users to create, view, filter, and delete contact entries efficiently.
tags:
  - name: Contacts
    description: Endpoints for managing contacts.
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-alrf.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
